#!/bin/zsh
set -e

if [[ $# -ne 1 ]]; then
	exit 1
fi

cat <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
EOF

while read f; do
	cat <<EOF
	<match>
		<test qual="any" name="family"><string>$f</string></test>
		<edit name="family" mode="assign_replace" binding="same"><string>$1</string></edit>
	</match>
EOF
done

cat <<EOF
</fontconfig>
EOF
