(define b xbindkey)
(b '(mod4 o)                "fmlove love")
(b '(mod4 d)                "dmenu_run")
(b '(mod4 g)                "copyq toggle")
(b '(mod4 slash)            "clipscreen-open")
(b '(mod4 semicolon)        "clipscreen-save")
(b '(mod4 apostrophe)       "clipscreen-upload")
(b '(mod4 F8)               "systemctl suspend")
(b '(shift mod4 d)          "pavucontrol")
(b '(mod4 F10)              "deadbeef --toggle-pause")
(b '(mod4 F11)              "deadbeef --prev")
(b '(mod4 F12)              "deadbeef --next")
(b '(mod4 c)                "xclip -o|(echo -n '\"'; cat; echo -n '\"')|xclip")
(b '(XF86AudioMute)         "pactl set-sink-mute 2 toggle")
(b '(XF86AudioLowerVolume)  "pactl set-sink-volume 2 '-5%'")
(b '(XF86AudioRaiseVolume)  "pactl set-sink-volume 2 '+5%'")
(b '(mod4 KP_Add)           "websearch $(xclip -o)")
(b '(mod4 z)                "websearch $(xclip -o)")
(b '(mod4 Prior)            "xclip -d :7 -o|xclip")
(b '(mod4 Next)             "xclip -o|xclip -d :7")
(b '(shift mod4 s)          "nautilus")
